
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fredrich
 */
public class datasakit extends javax.swing.JFrame {
    private Statement st;
    private Connection conn;
    private ResultSet rs;
    private String Sql;
    private String nama,NIP,email,pekerjaan,kondisi,penyakit,cuti;
    

    /**
     * Creates new form datasakit
     * @throws java.sql.SQLException
     */
    public datasakit() throws SQLException {
        initComponents();
        KoneksiDatabase();
        TampilkanTable("SELECT * FROM INPUT_SAKIT ");
    }
    
    private void clearobject(){
        txtnama.setText("");
        txtnip.setText("");
        txtemail.setText("");
        cbpekerjaan.setSelectedItem(null);
        
    }
    private void KoneksiDatabase(){
        try {
            //untuk menentukan driver database
            Class.forName("com.mysql.jdbc.Driver");
            //untuk membuat koneksi database ke driver
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/datakesehatan","root","");
            //memberrikan pesan terkoneksi
            JOptionPane.showMessageDialog(null, "Berhasil Terkoneksi");
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            //apabila gagal terkoneksi
            System.out.println("Koneksi gagal"+e.getMessage());
            
        }
    }
    private void TampilkanTable(String Sql) throws SQLException{
        DefaultTableModel kolom = new DefaultTableModel();
        kolom.addColumn("No");
        kolom.addColumn("Nama");
        kolom.addColumn("NIP");
        kolom.addColumn("Email");
        kolom.addColumn("Pekerjaan");
        kolom.addColumn("Kondisi");
        kolom.addColumn("Penyakit");
        kolom.addColumn("Cuti (Hari)");
        try {
            int nomor = 1;
            st  = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM INPUT_SAKIT");
            while (rs.next()){
                kolom.addRow(new Object[]{
                    (""+nomor++),
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7)
                });  
                tablesakit.setModel(kolom);
                tablesakit.enable(false);
                txtnama.requestFocus();
            } 
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null ,"Gagal Menampilkan /n" + e);
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtnip = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtpenyakit = new javax.swing.JTextField();
        txtcuti = new javax.swing.JTextField();
        bttanbah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btcancle = new javax.swing.JToggleButton();
        btkeluar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesakit = new javax.swing.JTable();
        cbpekerjaan = new javax.swing.JComboBox<>();
        cbkondisi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data Pegawai Sakit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 11, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        jLabel3.setText("NIP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, -1, -1));

        jLabel5.setText("Pekerjaan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setText("Kondisi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, -1, -1));

        jLabel7.setText("Penyakit");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 236, -1, -1));

        jLabel8.setText("Cuti (Hari)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 274, -1, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 43, 114, -1));
        getContentPane().add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 81, 114, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 119, 114, -1));
        getContentPane().add(txtpenyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 236, 114, -1));
        getContentPane().add(txtcuti, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 274, 114, -1));

        bttanbah.setText("Tambahkan");
        bttanbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttanbahActionPerformed(evt);
            }
        });
        getContentPane().add(bttanbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 333, -1, -1));

        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        getContentPane().add(btedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 333, 69, -1));

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 333, -1, -1));

        btcancle.setText("Cancel");
        btcancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancleActionPerformed(evt);
            }
        });
        getContentPane().add(btcancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 333, -1, -1));

        btkeluar.setText("Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 333, -1, -1));

        tablesakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablesakit);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 460, 290));

        cbpekerjaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Market Analyzer", "Data Scientist", "Web developer", "Network Engineer", "Software Engineer" }));
        getContentPane().add(cbpekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 157, -1, -1));

        cbkondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sakit" }));
        getContentPane().add(cbkondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 195, 114, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        nama = txtnama.getText();
        NIP = txtnip.getText();
        email = txtemail.getText();
        pekerjaan = cbpekerjaan.getItemAt(cbpekerjaan.getSelectedIndex()).toString();
        kondisi = cbkondisi.getItemAt(cbkondisi.getSelectedIndex()).toString();
        penyakit = txtpenyakit.getText();
        cuti = txtcuti.getText();
        try {
            Sql = "UPDATE input_sakit set NAMA ='"+nama+"',   email ='"+email+"' , pekerjaan ='"+pekerjaan+"',kondisi ='"+kondisi+"' ,penyakit ='"+penyakit+"', cuti = '"+cuti+"' WHERE NIP = '"+NIP+"' ";
            st=conn.createStatement();
            st.execute(Sql);
            TampilkanTable("SELECT * FROM input_sakit ");
            clearobject();
            JOptionPane.showMessageDialog(rootPane, "Data berhasil diupdate");
            txtnama.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan! /n " +e.getMessage());
        }
    }//GEN-LAST:event_bteditActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_btkeluarActionPerformed

    private void bttanbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttanbahActionPerformed
        // TODO add your handling code here:
        nama = txtnama.getText();
        NIP = txtnip.getText();
        email = txtemail.getText();
        pekerjaan = cbpekerjaan.getItemAt(cbpekerjaan.getSelectedIndex()).toString();
        kondisi = cbkondisi.getItemAt(cbkondisi.getSelectedIndex()).toString();
        penyakit =txtpenyakit.getText();
        cuti = txtcuti.getText();

        try {
            Sql = "INSERT INTO input_sakit (NAMA, NIP, EMAIL , PEKERJAAN, KONDISI, penyakit, cuti) "
            + "VALUES('"+nama+"' , '"+NIP+"' , '"+email+"' , '"+pekerjaan+"' ,'"+kondisi+"' , '"+penyakit+"' , '"+cuti+"' )";
            st = conn.createStatement();
            st.execute(Sql);
            TampilkanTable("SELECT * FROM input_sehat");
            clearobject();
            JOptionPane.showMessageDialog(rootPane, "Data telah terinput");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR! \n" +e);
        }

        
        
    }//GEN-LAST:event_bttanbahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        nama = txtnama.getText();
        try {
            Sql = "DELETE FROM INPUT_Sakit WHERE nama='"+nama+"'";
            st = conn.createStatement();
            st.execute(Sql);
            TampilkanTable(Sql);
            clearobject();
            txtnama.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "data telah terhapus");
            TampilkanTable("SELECT * FROM input_sakit");
            clearobject();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "gagal terhapus \n"+e.getMessage());
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btcancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancleActionPerformed
        // TODO add your handling code here:
        clearobject();
        txtnama.requestFocus();
    }//GEN-LAST:event_btcancleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datasakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datasakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datasakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datasakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new datasakit().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(datasakit.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btcancle;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JToggleButton btkeluar;
    private javax.swing.JButton bttanbah;
    private javax.swing.JComboBox<String> cbkondisi;
    private javax.swing.JComboBox<String> cbpekerjaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablesakit;
    private javax.swing.JTextField txtcuti;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpenyakit;
    // End of variables declaration//GEN-END:variables
}
