
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fredrich
 */
public class datasehat extends javax.swing.JFrame {
    private Statement st;
    private Connection conn;
    private ResultSet rs;
    private String Sql;
    
    private String nama,NIP, email, pekerjaan, kondisi ; 
    
    
            

    /**
     * Creates new form datasehat
     * @throws java.sql.SQLException
     */
    public datasehat() {
        initComponents();
        KoneksiDatabase();
        TampilDataTabel();
    }
    private void clearobject(){
        txtNama.setText("");
        txtNIP.setText("");
        txtemail.setText("");
        cbpekerjaan.setSelectedItem(null); 
    }
    private void KoneksiDatabase(){
        try {
            //untuk menentukan driver database
            Class.forName("com.mysql.jdbc.Driver");
            //untuk membuat koneksi database ke driver
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/datakesehatan","root","");
            //memberrikan pesan terkoneksi
            JOptionPane.showMessageDialog(null, "Berhasil Terkoneksi");
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            //apabila gagal terkoneksi
            System.out.println("Koneksi gagal"+e.getMessage());
        }
    }
    
    public void TampilDataTabel(){
        DefaultTableModel kolom = new DefaultTableModel();
        kolom.addColumn("No");
        kolom.addColumn("NIP");
        kolom.addColumn("Nama");
        kolom.addColumn("Email");
        kolom.addColumn("Pekerjaan");
        kolom.addColumn("Kondisi");
        try {
            int nomor = 1;
             st = conn.createStatement();
             rs = st.executeQuery("SELECT * FROM input_sehat");
             while(rs.next()){
                 kolom.addRow(new Object[]{
                     (""+nomor++),rs.getString("NIP"),
                     rs.getString("Nama"),
                     rs.getString(3),
                     rs.getString(4),
                     rs.getString(5)
                 });
                 tablesehat.setModel(kolom);
                 tablesehat.enable(false);
                 txtNama.requestFocus();
             }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null,"gagal menampilkan data \n" +e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNIP = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        cbpekerjaan = new javax.swing.JComboBox<>();
        cbkondisi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesehat = new javax.swing.JTable();
        btntambah = new javax.swing.JToggleButton();
        btnhapus = new javax.swing.JToggleButton();
        btnedit = new javax.swing.JToggleButton();
        btncancel = new javax.swing.JToggleButton();
        btnkeluar = new javax.swing.JToggleButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel1.setText("Data Pegawai Sehat");

        jLabel2.setText("Nama");

        jLabel4.setText("NIP");

        jLabel5.setText("Email");

        jLabel6.setText("Pekerjaan");

        jLabel7.setText("Kondisi");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
        });

        txtNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIPActionPerformed(evt);
            }
        });

        cbpekerjaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Market Analyzer", "Data Scientist", "Web developer", "Network Engineer", "Software Engineer" }));

        cbkondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sehat" }));

        tablesehat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablesehat);

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncancel)
                                .addGap(22, 22, 22)
                                .addComponent(btnkeluar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama)
                                    .addComponent(txtNIP)
                                    .addComponent(txtemail)
                                    .addComponent(cbpekerjaan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbkondisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbkondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnhapus)
                    .addComponent(btnedit)
                    .addComponent(btncancel)
                    .addComponent(btnkeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIPActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        nama = txtNama.getText();
        NIP = txtNIP.getText();
        email = txtemail.getText();
        pekerjaan = cbpekerjaan.getItemAt(cbpekerjaan.getSelectedIndex()).toString();
        kondisi = cbkondisi.getItemAt(cbkondisi.getSelectedIndex()).toString();

        try {
            Sql = "INSERT INTO input_sehat (NAMA, NIP, EMAIL , PEKERJAAN, KONDISI) "
            + "VALUES('"+nama+"' , '"+NIP+"' , '"+email+"' , '"+pekerjaan+"' ,'"+kondisi+"' )" ;
            st = conn.createStatement();
            st.execute(Sql);
            TampilDataTabel();
            clearobject();
            JOptionPane.showMessageDialog(rootPane, "Data telah terinput");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR! \n" +e);
        }

    }//GEN-LAST:event_btntambahActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        nama = txtNama.getText();
        NIP = txtNIP.getText();
        email = txtemail.getText();
        pekerjaan = cbpekerjaan.getItemAt(cbpekerjaan.getSelectedIndex()).toString();
        kondisi = cbkondisi.getItemAt(cbkondisi.getSelectedIndex()).toString();
        try {
            Sql = "UPDATE INPUT_SEHAT SET nama='"+nama+"' ,email='"+email+"' ,pekerjaan='"+pekerjaan+"' , kondisi='"+kondisi+"' WHERE nip = '"+NIP+"'  ";
            st=conn.createStatement();
            st.execute(Sql);
            TampilDataTabel();
            clearobject();
            JOptionPane.showMessageDialog(rootPane, "Data berhasil diupdate");
            txtNama.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan! /n " +e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNamaKeyPressed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        nama = txtNama.getText();
        try {
            Sql = "DELETE FROM INPUT_SEHAT WHERE nama='"+nama+"'";
            st = conn.createStatement();
            st.execute(Sql);
            TampilDataTabel();
            clearobject();
            txtNama.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "data telah terhapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "gagal terhapus \n"+e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        clearobject();
        txtNama.requestFocus();
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datasehat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datasehat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datasehat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datasehat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new datasehat().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btncancel;
    private javax.swing.JToggleButton btnedit;
    private javax.swing.JToggleButton btnhapus;
    private javax.swing.JToggleButton btnkeluar;
    private javax.swing.JToggleButton btntambah;
    private javax.swing.JComboBox<String> cbkondisi;
    private javax.swing.JComboBox<String> cbpekerjaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablesehat;
    private javax.swing.JTextField txtNIP;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
